---
spring:
  kafka:
    defaultConcurrency: 1
    server: ${KAFKA_HOST:localhost:9092}
    enabled: ${KAFKA_ENABLED:true}
    autoStartUp: true
    topics:
      eventDRCNotificationRequest: event.vxp.push.participant
      externalApiRequestLogs: event.vrp.externalApiRequestLogs
      vxpResponse: event.vxp.workflow.outbound
      pushParticipant: event.vxp.push.participant
      fulfillment:
        response: event.vxp.fulfillment.order.response
  datasource:
    platform: mysql
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/drc?autoreconnect=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: false
    hibernate:
      ddl-auto: none

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz:
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 8
        scheduler:
          batchTriggerAcquisitionMaxCount: 100
          skipUpdateCheck: true
          dbFailureRetryInterval: 15000
          idleWaitTime: 30000
          instanceId: AUTO
          instanceName: quartz-drc-app
          autoStartup: true
          startupDelay: 0
          classLoadHelper:
            class: org.quartz.simpl.ThreadContextClassLoadHelper
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          tablePrefix: QRTZ_
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          isClustered: true
          misfireThreshold: 60000
          clusterCheckinInterval: 20000

vibrent:
  oidc-auth:
    keycloak:
      baseAuthUrl: ${KEYCLOAK_BASEURL:https://keycloak-dev.vibrenthealth.com/auth}
      resourceId: ${KEYCLOAK_RESOURCEID:participant}
      participantRealm: ${KEYCLOAK_PARTICIPANT_REALM:default_participant_realm}
      enterpriseRealm: ${KEYCLOAK_ENTERPRISE_REALM:default_realm}
      enabled: ${KEYCLOAK_PARTICIPANT_ENABLED:true}
      drcInternalClientId: ${DRC_INTERNAL_CLIENT_ID:drc-internal-client}
      drcInternalClientSecret: ${CLIENT_CREDENTIAL_DRC_INTERNAL_SECRET:49234c9f-ac3b-4c22-9c76-b698eacdccba}
  drc:
    apiUrl: ${DRC_BASE_URL:https://pmi-drc-api-test.appspot.com/rdr/v1}
    postprocess: ${DRC_ENABLED:true}
    timeout: ${DRC_TIMEOUT:90000}
    drcCertificateFilePath: ${DRC_CERTIFICATE_FILE_PATH:/opt/data/drc/cert.json}
    genomics:
      participantStatus:
        batchProcessingSize: ${DRC_GENOMIC_BATCH_PROCESSING_SIZE:100}
        cron: ${DRC_GENOMIC_PARTICIPANT_STATUS:0 0 0/6 ? * * *}
      participantBatch:
        cron: ${DRC_GENOMIC_PARTICIPANT_BATCH_PROCESSING:0 0/15 * ? * * *}
    supplyStatus:
      enabled: ${SUPPLY_STATUS_ENABLED:false}
    accountInfoUpdates:
      enabled: ${ACCOUNT_INFO_UPDATES_ENABLED:true}
    sync:
      retry:
        cron: ${DRC_UPDATE_INFO_SYNC_RETRY_CRON:0 0 0/1 1/1 * ? *}
        maxRetryCount: ${DRC_UPDATE_INFO_SYNC_MAX_RETRY_COUNT:10}
    genomicSchedulingWorkflow:
      enabled: ${GENOMIC_SCHEDULING_WORKFLOW_ENABLED:true}

    forms:
      basics:
        id: ${BASICS_FORM_ID:284}
        name: ${BASICS_FORM_NAME:TheBasics}

  drc-service:
    acadiaApiUrl: ${API_SERVER:https://sub-default.qak8s.vibrenthealth.com}
    genotekUrl: ${GENOTEK_HOST_URL:https://sub-default.qak8s.vibrenthealth.com}/api/v1/
    fulfillmentUrl: ${FULFILLMENT_HOST_URL:https://sub-default.qak8s.vibrenthealth.com}/api/fulfillment/v1/
    caffeineSpec: ${CAFFEINE_CACHE_SPEC:maximumSize=150000}
    retryApiCall:
      retryForHttpStatusCode: ${RETRY_FOR_HTTP_STATUS_CODE:401,403,408,500,503,504,507,509}

externalLog:
  # default externalLog request/response body max size
  maxBodySize: ${EXT_LOG_BODY_MAX:128000}
redis:
  properties:
    redisson-ssl-enaled: ${REDIS_SSL_ENABLED:false}
    redisson-address: ${REDIS_URL:localhost:6379}
    redisson-is-clustered: ${IS_REDIS_CLUSTERED:false}
    redisson-cluster-type: ${REDIS_CLUSTER_TYPE:replicated}
    redisson-config: classpath:config/redisson-ss.yml
    redisson-replicated-config: classpath:config/redisson-replicated.yml
    redisson-cluster-config: classpath:config/redisson-cluster.yml

# Metrics related configurations
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
