package com.vibrent.drc.constants;

import java.util.HashMap;
import java.util.Map;

public class SecondaryContactStateRelationshipMaps {
    private static final String PERSON_ONE_ADDRESS_STATE_AL = "PersonOneAddressState_AL";
    private static final String PERSON_ONE_ADDRESS_STATE_AK = "PersonOneAddressState_AK";
    private static final String PERSON_ONE_ADDRESS_STATE_AS = "PersonOneAddressState_AS";
    private static final String PERSON_ONE_ADDRESS_STATE_AZ = "PersonOneAddressState_AZ";
    private static final String PERSON_ONE_ADDRESS_STATE_AR = "PersonOneAddressState_AR";
    private static final String PERSON_ONE_ADDRESS_STATE_CA = "PersonOneAddressState_CA";
    private static final String PERSON_ONE_ADDRESS_STATE_CO = "PersonOneAddressState_CO";
    private static final String PERSON_ONE_ADDRESS_STATE_CT = "PersonOneAddressState_CT";
    private static final String PERSON_ONE_ADDRESS_STATE_DE = "PersonOneAddressState_DE";
    private static final String PERSON_ONE_ADDRESS_STATE_DC = "PersonOneAddressState_DC";
    private static final String PERSON_ONE_ADDRESS_STATE_FM = "PersonOneAddressState_FM";
    private static final String PERSON_ONE_ADDRESS_STATE_FL = "PersonOneAddressState_FL";
    private static final String PERSON_ONE_ADDRESS_STATE_GA = "PersonOneAddressState_GA";
    private static final String PERSON_ONE_ADDRESS_STATE_GU = "PersonOneAddressState_GU";
    private static final String PERSON_ONE_ADDRESS_STATE_HI = "PersonOneAddressState_HI";
    private static final String PERSON_ONE_ADDRESS_STATE_ID = "PersonOneAddressState_ID";
    private static final String PERSON_ONE_ADDRESS_STATE_IL = "PersonOneAddressState_IL";
    private static final String PERSON_ONE_ADDRESS_STATE_IN = "PersonOneAddressState_IN";
    private static final String PERSON_ONE_ADDRESS_STATE_IA = "PersonOneAddressState_IA";
    private static final String PERSON_ONE_ADDRESS_STATE_KS = "PersonOneAddressState_KS";
    private static final String PERSON_ONE_ADDRESS_STATE_KY = "PersonOneAddressState_KY";
    private static final String PERSON_ONE_ADDRESS_STATE_LA = "PersonOneAddressState_LA";
    private static final String PERSON_ONE_ADDRESS_STATE_ME = "PersonOneAddressState_ME";
    private static final String PERSON_ONE_ADDRESS_STATE_MH = "PersonOneAddressState_MH";
    private static final String PERSON_ONE_ADDRESS_STATE_MD = "PersonOneAddressState_MD";
    private static final String PERSON_ONE_ADDRESS_STATE_MA = "PersonOneAddressState_MA";
    private static final String PERSON_ONE_ADDRESS_STATE_MI = "PersonOneAddressState_MI";
    private static final String PERSON_ONE_ADDRESS_STATE_MN = "PersonOneAddressState_MN";
    private static final String PERSON_ONE_ADDRESS_STATE_MS = "PersonOneAddressState_MS";
    private static final String PERSON_ONE_ADDRESS_STATE_MO = "PersonOneAddressState_MO";
    private static final String PERSON_ONE_ADDRESS_STATE_MT = "PersonOneAddressState_MT";
    private static final String PERSON_ONE_ADDRESS_STATE_NE = "PersonOneAddressState_NE";
    private static final String PERSON_ONE_ADDRESS_STATE_NV = "PersonOneAddressState_NV";
    private static final String PERSON_ONE_ADDRESS_STATE_NH = "PersonOneAddressState_NH";
    private static final String PERSON_ONE_ADDRESS_STATE_NJ = "PersonOneAddressState_NJ";
    private static final String PERSON_ONE_ADDRESS_STATE_NM = "PersonOneAddressState_NM";
    private static final String PERSON_ONE_ADDRESS_STATE_NY = "PersonOneAddressState_NY";
    private static final String PERSON_ONE_ADDRESS_STATE_NC = "PersonOneAddressState_NC";
    private static final String PERSON_ONE_ADDRESS_STATE_ND = "PersonOneAddressState_ND";
    private static final String PERSON_ONE_ADDRESS_STATE_MP = "PersonOneAddressState_MP";
    private static final String PERSON_ONE_ADDRESS_STATE_OH = "PersonOneAddressState_OH";
    private static final String PERSON_ONE_ADDRESS_STATE_OK = "PersonOneAddressState_OK";
    private static final String PERSON_ONE_ADDRESS_STATE_OR = "PersonOneAddressState_OR";
    private static final String PERSON_ONE_ADDRESS_STATE_PW = "PersonOneAddressState_PW";
    private static final String PERSON_ONE_ADDRESS_STATE_PA = "PersonOneAddressState_PA";
    private static final String PERSON_ONE_ADDRESS_STATE_PR = "PersonOneAddressState_PR";
    private static final String PERSON_ONE_ADDRESS_STATE_RI = "PersonOneAddressState_RI";
    private static final String PERSON_ONE_ADDRESS_STATE_SC = "PersonOneAddressState_SC";
    private static final String PERSON_ONE_ADDRESS_STATE_SD = "PersonOneAddressState_SD";
    private static final String PERSON_ONE_ADDRESS_STATE_TN = "PersonOneAddressState_TN";
    private static final String PERSON_ONE_ADDRESS_STATE_TX = "PersonOneAddressState_TX";
    private static final String PERSON_ONE_ADDRESS_STATE_UT = "PersonOneAddressState_UT";
    private static final String PERSON_ONE_ADDRESS_STATE_VT = "PersonOneAddressState_VT";
    private static final String PERSON_ONE_ADDRESS_STATE_VA = "PersonOneAddressState_VA";
    private static final String PERSON_ONE_ADDRESS_STATE_VI = "PersonOneAddressState_VI";
    private static final String PERSON_ONE_ADDRESS_STATE_WA = "PersonOneAddressState_WA";
    private static final String PERSON_ONE_ADDRESS_STATE_WV = "PersonOneAddressState_WV";
    private static final String PERSON_ONE_ADDRESS_STATE_WI = "PersonOneAddressState_WI";
    private static final String PERSON_ONE_ADDRESS_STATE_WY = "PersonOneAddressState_WY";
    private static final String PERSON_ONE_RELATIONSHIP_SPOUSE_PARTNER = "PersonOneRelationship_SpousePartner";
    private static final String PERSON_ONE_RELATIONSHIP_FRIEND = "PersonOneRelationship_Friend";
    private static final String PERSON_ONE_RELATIONSHIP_PARENT_GUARDIAN = "PersonOneRelationship_ParentGuardian";
    private static final String PERSON_ONE_RELATIONSHIP_CHILD = "PersonOneRelationship_Child";
    private static final String PERSON_ONE_RELATIONSHIP_RELATIVE = "PersonOneRelationship_Relative";
    private static final String SECOND_CONTACT_STATE_ALABAMA = "SecondContactState_Alabama";
    private static final String SECOND_CONTACT_STATE_ALASKA = "SecondContactState_Alaska";
    private static final String SECOND_CONTACT_STATE_AMERICAN_SAMOA = "SecondContactState_AmericanSamoa";
    private static final String SECOND_CONTACT_STATE_ARIZONA = "SecondContactState_Arizona";
    private static final String SECOND_CONTACT_STATE_ARKANSAS = "SecondContactState_Arkansas";
    private static final String SECOND_CONTACT_STATE_CALIFORNIA = "SecondContactState_California";
    private static final String SECOND_CONTACT_STATE_COLORADO = "SecondContactState_Colorado";
    private static final String SECOND_CONTACT_STATE_CONNECTICUT = "SecondContactState_Connecticut";
    private static final String SECOND_CONTACT_STATE_DELAWARE = "SecondContactState_Delaware";
    private static final String SECOND_CONTACT_STATE_DISTRICTOF_COLUMBIA = "SecondContactState_DistrictofColumbia";
    private static final String SECOND_CONTACT_STATE_FEDERATED_STATESOF_MICRONESIA = "SecondContactState_FederatedStatesofMicronesia";
    private static final String SECOND_CONTACT_STATE_FLORIDA = "SecondContactState_Florida";
    private static final String SECOND_CONTACT_STATE_GEORGIA = "SecondContactState_Georgia";
    private static final String SECOND_CONTACT_STATE_GUAM = "SecondContactState_Guam";
    private static final String SECOND_CONTACT_STATE_HAWAII = "SecondContactState_Hawaii";
    private static final String SECOND_CONTACT_STATE_IDAHO = "SecondContactState_Idaho";
    private static final String SECOND_CONTACT_STATE_ILLINOIS = "SecondContactState_Illinois";
    private static final String SECOND_CONTACT_STATE_INDIANA = "SecondContactState_Indiana";
    private static final String SECOND_CONTACT_STATE_IOWA = "SecondContactState_Iowa";
    private static final String SECOND_CONTACT_STATE_KANSAS = "SecondContactState_Kansas";
    private static final String SECOND_CONTACT_STATE_KENTUCKY = "SecondContactState_Kentucky";
    private static final String SECOND_CONTACT_STATE_LOUISIANA = "SecondContactState_Louisiana";
    private static final String SECOND_CONTACT_STATE_MAINE = "SecondContactState_Maine";
    private static final String SECOND_CONTACT_STATE_MARSHALL_ISLANDS = "SecondContactState_MarshallIslands";
    private static final String SECOND_CONTACT_STATE_MARYLAND = "SecondContactState_Maryland";
    private static final String SECOND_CONTACT_STATE_MASSACHUSETTS = "SecondContactState_Massachusetts";
    private static final String SECOND_CONTACT_STATE_MICHIGAN = "SecondContactState_Michigan";
    private static final String SECOND_CONTACT_STATE_MINNESOTA = "SecondContactState_Minnesota";
    private static final String SECOND_CONTACT_STATE_MISSISSIPPI = "SecondContactState_Mississippi";
    private static final String SECOND_CONTACT_STATE_MISSOURI = "SecondContactState_Missouri";
    private static final String SECOND_CONTACT_STATE_MONTANA = "SecondContactState_Montana";
    private static final String SECOND_CONTACT_STATE_NEBRASKA = "SecondContactState_Nebraska";
    private static final String SECOND_CONTACT_STATE_NEVADA = "SecondContactState_Nevada";
    private static final String SECOND_CONTACT_STATE_NEW_HAMPSHIRE = "SecondContactState_NewHampshire";
    private static final String SECOND_CONTACT_STATE_NEW_JERSEY = "SecondContactState_NewJersey";
    private static final String SECOND_CONTACT_STATE_NEW_MEXICO = "SecondContactState_NewMexico";
    private static final String SECOND_CONTACT_STATE_NEW_YORK = "SecondContactState_NewYork";
    private static final String SECOND_CONTACT_STATE_NORTH_CAROLINA = "SecondContactState_NorthCarolina";
    private static final String SECOND_CONTACT_STATE_NORTH_DAKOTA = "SecondContactState_NorthDakota";
    private static final String SECOND_CONTACT_STATE_NORTH_MARIANAS_ISLANDS = "SecondContactState_NorthMarianasIslands";
    private static final String SECOND_CONTACT_STATE_OHIO = "SecondContactState_Ohio";
    private static final String SECOND_CONTACT_STATE_OKLAHOMA = "SecondContactState_Oklahoma";
    private static final String SECOND_CONTACT_STATE_OREGON = "SecondContactState_Oregon";
    private static final String SECOND_CONTACT_STATE_PALAU = "SecondContactState_Palau";
    private static final String SECOND_CONTACT_STATE_PENNSYLVANIA = "SecondContactState_Pennsylvania";
    private static final String SECOND_CONTACT_STATE_PUERTO_RICO = "SecondContactState_PuertoRico";
    private static final String SECOND_CONTACT_STATE_RHODE_ISLAND = "SecondContactState_RhodeIsland";
    private static final String SECOND_CONTACT_STATE_SOUTH_CAROLINA = "SecondContactState_SouthCarolina";
    private static final String SECOND_CONTACT_STATE_SOUTH_DAKOTA = "SecondContactState_SouthDakota";
    private static final String SECOND_CONTACT_STATE_TENNESSEE = "SecondContactState_Tennessee";
    private static final String SECOND_CONTACT_STATE_TEXAS = "SecondContactState_Texas";
    private static final String SECOND_CONTACT_STATE_UTAH = "SecondContactState_Utah";
    private static final String SECOND_CONTACT_STATE_VERMONT = "SecondContactState_Vermont";
    private static final String SECOND_CONTACT_STATE_VIRGINIA = "SecondContactState_Virginia";
    private static final String SECOND_CONTACT_STATE_VIRGIN_ISLANDS = "SecondContactState_VirginIslands";
    private static final String SECOND_CONTACT_STATE_WASHINGTON = "SecondContactState_Washington";
    private static final String SECOND_CONTACT_STATE_WEST_VIRGINIA = "SecondContactState_WestVirginia";
    private static final String SECOND_CONTACT_STATE_WISCONSIN = "SecondContactState_Wisconsin";
    private static final String SECOND_CONTACT_STATE_WYOMING = "SecondContactState_Wyoming";
    private static final String SECOND_CONTACTS_RELATIONSHIP_SPOUSE_PARTNER = "SecondContactsRelationship_SpousePartner";
    private static final String SECOND_CONTACTS_RELATIONSHIP_FRIEND = "SecondContactsRelationship_Friend";
    private static final String SECOND_CONTACTS_RELATIONSHIP_PARENT_GUARDIAN = "SecondContactsRelationship_ParentGuardian";
    private static final String SECOND_CONTACTS_RELATIONSHIP_CHILD = "SecondContactsRelationship_Child";
    private static final String SECOND_CONTACTS_RELATIONSHIP_RELATIVE = "SecondContactsRelationship_Relative";

    private static final String PIISTATE_AL = "PIIState_AL";
    private static final String PIISTATE_AK = "PIIState_AK";
    private static final String PIISTATE_AS = "PIIState_AS";
    private static final String PIISTATE_AZ = "PIIState_AZ";
    private static final String PIISTATE_AR = "PIIState_AR";
    private static final String PIISTATE_CA = "PIIState_CA";
    private static final String PIISTATE_CO = "PIIState_CO";
    private static final String PIISTATE_CT = "PIIState_CT";
    private static final String PIISTATE_DE = "PIIState_DE";
    private static final String PIISTATE_DC = "PIIState_DC";
    private static final String PIISTATE_FM = "PIIState_FM";
    private static final String PIISTATE_FL = "PIIState_FL";
    private static final String PIISTATE_GA = "PIIState_GA";
    private static final String PIISTATE_GU = "PIIState_GU";
    private static final String PIISTATE_HI = "PIIState_HI";
    private static final String PIISTATE_ID = "PIIState_ID";
    private static final String PIISTATE_IL = "PIIState_IL";
    private static final String PIISTATE_IN = "PIIState_IN";
    private static final String PIISTATE_IA = "PIIState_IA";
    private static final String PIISTATE_KS = "PIIState_KS";
    private static final String PIISTATE_KY = "PIIState_KY";
    private static final String PIISTATE_LA = "PIIState_LA";
    private static final String PIISTATE_ME = "PIIState_ME";
    private static final String PIISTATE_MH = "PIIState_MH";
    private static final String PIISTATE_MD = "PIIState_MD";
    private static final String PIISTATE_MA = "PIIState_MA";
    private static final String PIISTATE_MI = "PIIState_MI";
    private static final String PIISTATE_MN = "PIIState_MN";
    private static final String PIISTATE_MS = "PIIState_MS";
    private static final String PIISTATE_MO = "PIIState_MO";
    private static final String PIISTATE_MT = "PIIState_MT";
    private static final String PIISTATE_NE = "PIIState_NE";
    private static final String PIISTATE_NV = "PIIState_NV";
    private static final String PIISTATE_NH = "PIIState_NH";
    private static final String PIISTATE_NJ = "PIIState_NJ";
    private static final String PIISTATE_NM = "PIIState_NM";
    private static final String PIISTATE_NY = "PIIState_NY";
    private static final String PIISTATE_NC = "PIIState_NC";
    private static final String PIISTATE_ND = "PIIState_ND";
    private static final String PIISTATE_MP = "PIIState_MP";
    private static final String PIISTATE_OH = "PIIState_OH";
    private static final String PIISTATE_OK = "PIIState_OK";
    private static final String PIISTATE_OR = "PIIState_OR";
    private static final String PIISTATE_PW = "PIIState_PW";
    private static final String PIISTATE_PA = "PIIState_PA";
    private static final String PIISTATE_PR = "PIIState_PR";
    private static final String PIISTATE_RI = "PIIState_RI";
    private static final String PIISTATE_SC = "PIIState_SC";
    private static final String PIISTATE_SD = "PIIState_SD";
    private static final String PIISTATE_TN = "PIIState_TN";
    private static final String PIISTATE_TX = "PIIState_TX";
    private static final String PIISTATE_UT = "PIIState_UT";
    private static final String PIISTATE_VT = "PIIState_VT";
    private static final String PIISTATE_VA = "PIIState_VA";
    private static final String PIISTATE_VI = "PIIState_VI";
    private static final String PIISTATE_WA = "PIIState_WA";
    private static final String PIISTATE_WV = "PIIState_WV";
    private static final String PIISTATE_WI = "PIIState_WI";
    private static final String PIISTATE_WY = "PIIState_WY";

    private static final String PARTNER = "partner";
    private static final String FRIEND = "friend";
    private static final String PARENT = "parent";
    private static final String CHILD = "child";
    private static final String RELATIVE = "relative";

    private SecondaryContactStateRelationshipMaps() {
    }

    public static Map<String, String> getSecondaryContactStateRelationshipMap() {

        Map<String, String> map = new HashMap<>();
        map.put(PERSON_ONE_ADDRESS_STATE_AL, PIISTATE_AL);
        map.put(PERSON_ONE_ADDRESS_STATE_AK, PIISTATE_AK);
        map.put(PERSON_ONE_ADDRESS_STATE_AS, PIISTATE_AS);
        map.put(PERSON_ONE_ADDRESS_STATE_AZ, PIISTATE_AZ);
        map.put(PERSON_ONE_ADDRESS_STATE_AR, PIISTATE_AR);
        map.put(PERSON_ONE_ADDRESS_STATE_CA, PIISTATE_CA);
        map.put(PERSON_ONE_ADDRESS_STATE_CO, PIISTATE_CO);
        map.put(PERSON_ONE_ADDRESS_STATE_CT, PIISTATE_CT);
        map.put(PERSON_ONE_ADDRESS_STATE_DE, PIISTATE_DE);
        map.put(PERSON_ONE_ADDRESS_STATE_DC, PIISTATE_DC);
        map.put(PERSON_ONE_ADDRESS_STATE_FM, PIISTATE_FM);
        map.put(PERSON_ONE_ADDRESS_STATE_FL, PIISTATE_FL);
        map.put(PERSON_ONE_ADDRESS_STATE_GA, PIISTATE_GA);
        map.put(PERSON_ONE_ADDRESS_STATE_GU, PIISTATE_GU);
        map.put(PERSON_ONE_ADDRESS_STATE_HI, PIISTATE_HI);
        map.put(PERSON_ONE_ADDRESS_STATE_ID, PIISTATE_ID);
        map.put(PERSON_ONE_ADDRESS_STATE_IL, PIISTATE_IL);
        map.put(PERSON_ONE_ADDRESS_STATE_IN, PIISTATE_IN);
        map.put(PERSON_ONE_ADDRESS_STATE_IA, PIISTATE_IA);
        map.put(PERSON_ONE_ADDRESS_STATE_KS, PIISTATE_KS);
        map.put(PERSON_ONE_ADDRESS_STATE_KY, PIISTATE_KY);
        map.put(PERSON_ONE_ADDRESS_STATE_LA, PIISTATE_LA);
        map.put(PERSON_ONE_ADDRESS_STATE_ME, PIISTATE_ME);
        map.put(PERSON_ONE_ADDRESS_STATE_MH, PIISTATE_MH);
        map.put(PERSON_ONE_ADDRESS_STATE_MD, PIISTATE_MD);
        map.put(PERSON_ONE_ADDRESS_STATE_MA, PIISTATE_MA);
        map.put(PERSON_ONE_ADDRESS_STATE_MI, PIISTATE_MI);
        map.put(PERSON_ONE_ADDRESS_STATE_MN, PIISTATE_MN);
        map.put(PERSON_ONE_ADDRESS_STATE_MS, PIISTATE_MS);
        map.put(PERSON_ONE_ADDRESS_STATE_MO, PIISTATE_MO);
        map.put(PERSON_ONE_ADDRESS_STATE_MT, PIISTATE_MT);
        map.put(PERSON_ONE_ADDRESS_STATE_NE, PIISTATE_NE);
        map.put(PERSON_ONE_ADDRESS_STATE_NV, PIISTATE_NV);
        map.put(PERSON_ONE_ADDRESS_STATE_NH, PIISTATE_NH);
        map.put(PERSON_ONE_ADDRESS_STATE_NJ, PIISTATE_NJ);
        map.put(PERSON_ONE_ADDRESS_STATE_NM, PIISTATE_NM);
        map.put(PERSON_ONE_ADDRESS_STATE_NY, PIISTATE_NY);
        map.put(PERSON_ONE_ADDRESS_STATE_NC, PIISTATE_NC);
        map.put(PERSON_ONE_ADDRESS_STATE_ND, PIISTATE_ND);
        map.put(PERSON_ONE_ADDRESS_STATE_MP, PIISTATE_MP);
        map.put(PERSON_ONE_ADDRESS_STATE_OH, PIISTATE_OH);
        map.put(PERSON_ONE_ADDRESS_STATE_OK, PIISTATE_OK);
        map.put(PERSON_ONE_ADDRESS_STATE_OR, PIISTATE_OR);
        map.put(PERSON_ONE_ADDRESS_STATE_PW, PIISTATE_PW);
        map.put(PERSON_ONE_ADDRESS_STATE_PA, PIISTATE_PA);
        map.put(PERSON_ONE_ADDRESS_STATE_PR, PIISTATE_PR);
        map.put(PERSON_ONE_ADDRESS_STATE_RI, PIISTATE_RI);
        map.put(PERSON_ONE_ADDRESS_STATE_SC, PIISTATE_SC);
        map.put(PERSON_ONE_ADDRESS_STATE_SD, PIISTATE_SD);
        map.put(PERSON_ONE_ADDRESS_STATE_TN, PIISTATE_TN);
        map.put(PERSON_ONE_ADDRESS_STATE_TX, PIISTATE_TX);
        map.put(PERSON_ONE_ADDRESS_STATE_UT, PIISTATE_UT);
        map.put(PERSON_ONE_ADDRESS_STATE_VT, PIISTATE_VT);
        map.put(PERSON_ONE_ADDRESS_STATE_VA, PIISTATE_VA);
        map.put(PERSON_ONE_ADDRESS_STATE_VI, PIISTATE_VI);
        map.put(PERSON_ONE_ADDRESS_STATE_WA, PIISTATE_WA);
        map.put(PERSON_ONE_ADDRESS_STATE_WV, PIISTATE_WV);
        map.put(PERSON_ONE_ADDRESS_STATE_WI, PIISTATE_WI);
        map.put(PERSON_ONE_ADDRESS_STATE_WY, PIISTATE_WY);
        map.put(PERSON_ONE_RELATIONSHIP_SPOUSE_PARTNER, PARTNER);
        map.put(PERSON_ONE_RELATIONSHIP_FRIEND, FRIEND);
        map.put(PERSON_ONE_RELATIONSHIP_PARENT_GUARDIAN, PARENT);
        map.put(PERSON_ONE_RELATIONSHIP_CHILD, CHILD);
        map.put(PERSON_ONE_RELATIONSHIP_RELATIVE, RELATIVE);

        map.put(SECOND_CONTACT_STATE_ALABAMA, PIISTATE_AL);
        map.put(SECOND_CONTACT_STATE_ALASKA, PIISTATE_AK);
        map.put(SECOND_CONTACT_STATE_AMERICAN_SAMOA, PIISTATE_AS);
        map.put(SECOND_CONTACT_STATE_ARIZONA, PIISTATE_AZ);
        map.put(SECOND_CONTACT_STATE_ARKANSAS, PIISTATE_AR);
        map.put(SECOND_CONTACT_STATE_CALIFORNIA, PIISTATE_CA);
        map.put(SECOND_CONTACT_STATE_COLORADO, PIISTATE_CO);
        map.put(SECOND_CONTACT_STATE_CONNECTICUT, PIISTATE_CT);
        map.put(SECOND_CONTACT_STATE_DELAWARE, PIISTATE_DE);
        map.put(SECOND_CONTACT_STATE_DISTRICTOF_COLUMBIA, PIISTATE_DC);
        map.put(SECOND_CONTACT_STATE_FEDERATED_STATESOF_MICRONESIA, PIISTATE_FM);
        map.put(SECOND_CONTACT_STATE_FLORIDA, PIISTATE_FL);
        map.put(SECOND_CONTACT_STATE_GEORGIA, PIISTATE_GA);
        map.put(SECOND_CONTACT_STATE_GUAM, PIISTATE_GU);
        map.put(SECOND_CONTACT_STATE_HAWAII, PIISTATE_HI);
        map.put(SECOND_CONTACT_STATE_IDAHO, PIISTATE_ID);
        map.put(SECOND_CONTACT_STATE_ILLINOIS, PIISTATE_IL);
        map.put(SECOND_CONTACT_STATE_INDIANA, PIISTATE_IN);
        map.put(SECOND_CONTACT_STATE_IOWA, PIISTATE_IA);
        map.put(SECOND_CONTACT_STATE_KANSAS, PIISTATE_KS);
        map.put(SECOND_CONTACT_STATE_KENTUCKY, PIISTATE_KY);
        map.put(SECOND_CONTACT_STATE_LOUISIANA, PIISTATE_LA);
        map.put(SECOND_CONTACT_STATE_MAINE, PIISTATE_ME);
        map.put(SECOND_CONTACT_STATE_MARSHALL_ISLANDS, PIISTATE_MH);
        map.put(SECOND_CONTACT_STATE_MARYLAND, PIISTATE_MD);
        map.put(SECOND_CONTACT_STATE_MASSACHUSETTS, PIISTATE_MA);
        map.put(SECOND_CONTACT_STATE_MICHIGAN, PIISTATE_MI);
        map.put(SECOND_CONTACT_STATE_MINNESOTA, PIISTATE_MN);
        map.put(SECOND_CONTACT_STATE_MISSISSIPPI, PIISTATE_MS);
        map.put(SECOND_CONTACT_STATE_MISSOURI, PIISTATE_MO);
        map.put(SECOND_CONTACT_STATE_MONTANA, PIISTATE_MT);
        map.put(SECOND_CONTACT_STATE_NEBRASKA, PIISTATE_NE);
        map.put(SECOND_CONTACT_STATE_NEVADA, PIISTATE_NV);
        map.put(SECOND_CONTACT_STATE_NEW_HAMPSHIRE, PIISTATE_NH);
        map.put(SECOND_CONTACT_STATE_NEW_JERSEY, PIISTATE_NJ);
        map.put(SECOND_CONTACT_STATE_NEW_MEXICO, PIISTATE_NM);
        map.put(SECOND_CONTACT_STATE_NEW_YORK, PIISTATE_NY);
        map.put(SECOND_CONTACT_STATE_NORTH_CAROLINA, PIISTATE_NC);
        map.put(SECOND_CONTACT_STATE_NORTH_DAKOTA, PIISTATE_ND);
        map.put(SECOND_CONTACT_STATE_NORTH_MARIANAS_ISLANDS, PIISTATE_MP);
        map.put(SECOND_CONTACT_STATE_OHIO, PIISTATE_OH);
        map.put(SECOND_CONTACT_STATE_OKLAHOMA, PIISTATE_OK);
        map.put(SECOND_CONTACT_STATE_OREGON, PIISTATE_OR);
        map.put(SECOND_CONTACT_STATE_PALAU, PIISTATE_PW);
        map.put(SECOND_CONTACT_STATE_PENNSYLVANIA, PIISTATE_PA);
        map.put(SECOND_CONTACT_STATE_PUERTO_RICO, PIISTATE_PR);
        map.put(SECOND_CONTACT_STATE_RHODE_ISLAND, PIISTATE_RI);
        map.put(SECOND_CONTACT_STATE_SOUTH_CAROLINA, PIISTATE_SC);
        map.put(SECOND_CONTACT_STATE_SOUTH_DAKOTA, PIISTATE_SD);
        map.put(SECOND_CONTACT_STATE_TENNESSEE, PIISTATE_TN);
        map.put(SECOND_CONTACT_STATE_TEXAS, PIISTATE_TX);
        map.put(SECOND_CONTACT_STATE_UTAH, PIISTATE_UT);
        map.put(SECOND_CONTACT_STATE_VERMONT, PIISTATE_VT);
        map.put(SECOND_CONTACT_STATE_VIRGINIA, PIISTATE_VA);
        map.put(SECOND_CONTACT_STATE_VIRGIN_ISLANDS, PIISTATE_VI);
        map.put(SECOND_CONTACT_STATE_WASHINGTON, PIISTATE_WA);
        map.put(SECOND_CONTACT_STATE_WEST_VIRGINIA, PIISTATE_WV);
        map.put(SECOND_CONTACT_STATE_WISCONSIN, PIISTATE_WI);
        map.put(SECOND_CONTACT_STATE_WYOMING, PIISTATE_WY);
        map.put(SECOND_CONTACTS_RELATIONSHIP_SPOUSE_PARTNER, PARTNER);
        map.put(SECOND_CONTACTS_RELATIONSHIP_FRIEND, FRIEND);
        map.put(SECOND_CONTACTS_RELATIONSHIP_PARENT_GUARDIAN, PARENT);
        map.put(SECOND_CONTACTS_RELATIONSHIP_CHILD, CHILD);
        map.put(SECOND_CONTACTS_RELATIONSHIP_RELATIVE, RELATIVE);

        return map;
    }

    public static Map<String, String> getContactOneStateRelationshipDRCMap() {
        Map<String, String> map = new HashMap<>();
        map.put(PIISTATE_AL, PERSON_ONE_ADDRESS_STATE_AL);
        map.put(PIISTATE_AK, PERSON_ONE_ADDRESS_STATE_AK);
        map.put(PIISTATE_AS, PERSON_ONE_ADDRESS_STATE_AS);
        map.put(PIISTATE_AZ, PERSON_ONE_ADDRESS_STATE_AZ);
        map.put(PIISTATE_AR, PERSON_ONE_ADDRESS_STATE_AR);
        map.put(PIISTATE_CA, PERSON_ONE_ADDRESS_STATE_CA);
        map.put(PIISTATE_CO, PERSON_ONE_ADDRESS_STATE_CO);
        map.put(PIISTATE_CT, PERSON_ONE_ADDRESS_STATE_CT);
        map.put(PIISTATE_DE, PERSON_ONE_ADDRESS_STATE_DE);
        map.put(PIISTATE_DC, PERSON_ONE_ADDRESS_STATE_DC);
        map.put(PIISTATE_FM, PERSON_ONE_ADDRESS_STATE_FM);
        map.put(PIISTATE_FL, PERSON_ONE_ADDRESS_STATE_FL);
        map.put(PIISTATE_GA, PERSON_ONE_ADDRESS_STATE_GA);
        map.put(PIISTATE_GU, PERSON_ONE_ADDRESS_STATE_GU);
        map.put(PIISTATE_HI, PERSON_ONE_ADDRESS_STATE_HI);
        map.put(PIISTATE_ID, PERSON_ONE_ADDRESS_STATE_ID);
        map.put(PIISTATE_IL, PERSON_ONE_ADDRESS_STATE_IL);
        map.put(PIISTATE_IN, PERSON_ONE_ADDRESS_STATE_IN);
        map.put(PIISTATE_IA, PERSON_ONE_ADDRESS_STATE_IA);
        map.put(PIISTATE_KS, PERSON_ONE_ADDRESS_STATE_KS);
        map.put(PIISTATE_KY, PERSON_ONE_ADDRESS_STATE_KY);
        map.put(PIISTATE_LA, PERSON_ONE_ADDRESS_STATE_LA);
        map.put(PIISTATE_ME, PERSON_ONE_ADDRESS_STATE_ME);
        map.put(PIISTATE_MH, PERSON_ONE_ADDRESS_STATE_MH);
        map.put(PIISTATE_MD, PERSON_ONE_ADDRESS_STATE_MD);
        map.put(PIISTATE_MA, PERSON_ONE_ADDRESS_STATE_MA);
        map.put(PIISTATE_MI, PERSON_ONE_ADDRESS_STATE_MI);
        map.put(PIISTATE_MN, PERSON_ONE_ADDRESS_STATE_MN);
        map.put(PIISTATE_MS, PERSON_ONE_ADDRESS_STATE_MS);
        map.put(PIISTATE_MO, PERSON_ONE_ADDRESS_STATE_MO);
        map.put(PIISTATE_MT, PERSON_ONE_ADDRESS_STATE_MT);
        map.put(PIISTATE_NE, PERSON_ONE_ADDRESS_STATE_NE);
        map.put(PIISTATE_NV, PERSON_ONE_ADDRESS_STATE_NV);
        map.put(PIISTATE_NH, PERSON_ONE_ADDRESS_STATE_NH);
        map.put(PIISTATE_NJ, PERSON_ONE_ADDRESS_STATE_NJ);
        map.put(PIISTATE_NM, PERSON_ONE_ADDRESS_STATE_NM);
        map.put(PIISTATE_NY, PERSON_ONE_ADDRESS_STATE_NY);
        map.put(PIISTATE_NC, PERSON_ONE_ADDRESS_STATE_NC);
        map.put(PIISTATE_ND, PERSON_ONE_ADDRESS_STATE_ND);
        map.put(PIISTATE_MP, PERSON_ONE_ADDRESS_STATE_MP);
        map.put(PIISTATE_OH, PERSON_ONE_ADDRESS_STATE_OH);
        map.put(PIISTATE_OK, PERSON_ONE_ADDRESS_STATE_OK);
        map.put(PIISTATE_OR, PERSON_ONE_ADDRESS_STATE_OR);
        map.put(PIISTATE_PW, PERSON_ONE_ADDRESS_STATE_PW);
        map.put(PIISTATE_PA, PERSON_ONE_ADDRESS_STATE_PA);
        map.put(PIISTATE_PR, PERSON_ONE_ADDRESS_STATE_PR);
        map.put(PIISTATE_RI, PERSON_ONE_ADDRESS_STATE_RI);
        map.put(PIISTATE_SC, PERSON_ONE_ADDRESS_STATE_SC);
        map.put(PIISTATE_SD, PERSON_ONE_ADDRESS_STATE_SD);
        map.put(PIISTATE_TN, PERSON_ONE_ADDRESS_STATE_TN);
        map.put(PIISTATE_TX, PERSON_ONE_ADDRESS_STATE_TX);
        map.put(PIISTATE_UT, PERSON_ONE_ADDRESS_STATE_UT);
        map.put(PIISTATE_VT, PERSON_ONE_ADDRESS_STATE_VT);
        map.put(PIISTATE_VA, PERSON_ONE_ADDRESS_STATE_VA);
        map.put(PIISTATE_VI, PERSON_ONE_ADDRESS_STATE_VI);
        map.put(PIISTATE_WA, PERSON_ONE_ADDRESS_STATE_WA);
        map.put(PIISTATE_WV, PERSON_ONE_ADDRESS_STATE_WV);
        map.put(PIISTATE_WI, PERSON_ONE_ADDRESS_STATE_WI);
        map.put(PIISTATE_WY, PERSON_ONE_ADDRESS_STATE_WY);
        map.put(PARTNER, PERSON_ONE_RELATIONSHIP_SPOUSE_PARTNER);
        map.put(FRIEND, PERSON_ONE_RELATIONSHIP_FRIEND);
        map.put(PARENT, PERSON_ONE_RELATIONSHIP_PARENT_GUARDIAN);
        map.put(CHILD, PERSON_ONE_RELATIONSHIP_CHILD);
        map.put(RELATIVE, PERSON_ONE_RELATIONSHIP_RELATIVE);

        return map;
    }

    public static Map<String, String> getContactTwoStateRelationshipDRCMap() {

        Map<String, String> map = new HashMap<>();
        map.put(PIISTATE_AL, SECOND_CONTACT_STATE_ALABAMA);
        map.put(PIISTATE_AK, SECOND_CONTACT_STATE_ALASKA);
        map.put(PIISTATE_AS, SECOND_CONTACT_STATE_AMERICAN_SAMOA);
        map.put(PIISTATE_AZ, SECOND_CONTACT_STATE_ARIZONA);
        map.put(PIISTATE_AR, SECOND_CONTACT_STATE_ARKANSAS);
        map.put(PIISTATE_CA, SECOND_CONTACT_STATE_CALIFORNIA);
        map.put(PIISTATE_CO, SECOND_CONTACT_STATE_COLORADO);
        map.put(PIISTATE_CT, SECOND_CONTACT_STATE_CONNECTICUT);
        map.put(PIISTATE_DE, SECOND_CONTACT_STATE_DELAWARE);
        map.put(PIISTATE_DC, SECOND_CONTACT_STATE_DISTRICTOF_COLUMBIA);
        map.put(PIISTATE_FM, SECOND_CONTACT_STATE_FEDERATED_STATESOF_MICRONESIA);
        map.put(PIISTATE_FL, SECOND_CONTACT_STATE_FLORIDA);
        map.put(PIISTATE_GA, SECOND_CONTACT_STATE_GEORGIA);
        map.put(PIISTATE_GU, SECOND_CONTACT_STATE_GUAM);
        map.put(PIISTATE_HI, SECOND_CONTACT_STATE_HAWAII);
        map.put(PIISTATE_ID, SECOND_CONTACT_STATE_IDAHO);
        map.put(PIISTATE_IL, SECOND_CONTACT_STATE_ILLINOIS);
        map.put(PIISTATE_IN, SECOND_CONTACT_STATE_INDIANA);
        map.put(PIISTATE_IA, SECOND_CONTACT_STATE_IOWA);
        map.put(PIISTATE_KS, SECOND_CONTACT_STATE_KANSAS);
        map.put(PIISTATE_KY, SECOND_CONTACT_STATE_KENTUCKY);
        map.put(PIISTATE_LA, SECOND_CONTACT_STATE_LOUISIANA);
        map.put(PIISTATE_ME, SECOND_CONTACT_STATE_MAINE);
        map.put(PIISTATE_MH, SECOND_CONTACT_STATE_MARSHALL_ISLANDS);
        map.put(PIISTATE_MD, SECOND_CONTACT_STATE_MARYLAND);
        map.put(PIISTATE_MA, SECOND_CONTACT_STATE_MASSACHUSETTS);
        map.put(PIISTATE_MI, SECOND_CONTACT_STATE_MICHIGAN);
        map.put(PIISTATE_MN, SECOND_CONTACT_STATE_MINNESOTA);
        map.put(PIISTATE_MS, SECOND_CONTACT_STATE_MISSISSIPPI);
        map.put(PIISTATE_MO, SECOND_CONTACT_STATE_MISSOURI);
        map.put(PIISTATE_MT, SECOND_CONTACT_STATE_MONTANA);
        map.put(PIISTATE_NE, SECOND_CONTACT_STATE_NEBRASKA);
        map.put(PIISTATE_NV, SECOND_CONTACT_STATE_NEVADA);
        map.put(PIISTATE_NH, SECOND_CONTACT_STATE_NEW_HAMPSHIRE);
        map.put(PIISTATE_NJ, SECOND_CONTACT_STATE_NEW_JERSEY);
        map.put(PIISTATE_NM, SECOND_CONTACT_STATE_NEW_MEXICO);
        map.put(PIISTATE_NY, SECOND_CONTACT_STATE_NEW_YORK);
        map.put(PIISTATE_NC, SECOND_CONTACT_STATE_NORTH_CAROLINA);
        map.put(PIISTATE_ND, SECOND_CONTACT_STATE_NORTH_DAKOTA);
        map.put(PIISTATE_MP, SECOND_CONTACT_STATE_NORTH_MARIANAS_ISLANDS);
        map.put(PIISTATE_OH, SECOND_CONTACT_STATE_OHIO);
        map.put(PIISTATE_OK, SECOND_CONTACT_STATE_OKLAHOMA);
        map.put(PIISTATE_OR, SECOND_CONTACT_STATE_OREGON);
        map.put(PIISTATE_PW, SECOND_CONTACT_STATE_PALAU);
        map.put(PIISTATE_PA, SECOND_CONTACT_STATE_PENNSYLVANIA);
        map.put(PIISTATE_PR, SECOND_CONTACT_STATE_PUERTO_RICO);
        map.put(PIISTATE_RI, SECOND_CONTACT_STATE_RHODE_ISLAND);
        map.put(PIISTATE_SC, SECOND_CONTACT_STATE_SOUTH_CAROLINA);
        map.put(PIISTATE_SD, SECOND_CONTACT_STATE_SOUTH_DAKOTA);
        map.put(PIISTATE_TN, SECOND_CONTACT_STATE_TENNESSEE);
        map.put(PIISTATE_TX, SECOND_CONTACT_STATE_TEXAS);
        map.put(PIISTATE_UT, SECOND_CONTACT_STATE_UTAH);
        map.put(PIISTATE_VT, SECOND_CONTACT_STATE_VERMONT);
        map.put(PIISTATE_VA, SECOND_CONTACT_STATE_VIRGINIA);
        map.put(PIISTATE_VI, SECOND_CONTACT_STATE_VIRGIN_ISLANDS);
        map.put(PIISTATE_WA, SECOND_CONTACT_STATE_WASHINGTON);
        map.put(PIISTATE_WV, SECOND_CONTACT_STATE_WEST_VIRGINIA);
        map.put(PIISTATE_WI, SECOND_CONTACT_STATE_WISCONSIN);
        map.put(PIISTATE_WY, SECOND_CONTACT_STATE_WYOMING);
        map.put(PARTNER, SECOND_CONTACTS_RELATIONSHIP_SPOUSE_PARTNER);
        map.put(FRIEND, SECOND_CONTACTS_RELATIONSHIP_FRIEND);
        map.put(PARENT, SECOND_CONTACTS_RELATIONSHIP_PARENT_GUARDIAN);
        map.put(CHILD, SECOND_CONTACTS_RELATIONSHIP_CHILD);
        map.put(RELATIVE, SECOND_CONTACTS_RELATIONSHIP_RELATIVE);
        return map;
    }
}
